-- vim.api.nvim_create_autocmd({"BufNewFile", "BufRead"}, {
--     pattern = "*.blade.php",
--     callback = function()
--         vim.cmd("set ft=html")
--         vim.cmd("set ft=phtml")
--         vim.cmd("set ft=blade")
--     end
-- })
